# Generated by Django 2.0 on 2018-02-06 11:52

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(max_length=1024)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to=base.models.UniqueId('/items'))),
                ('instagram_url', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_id', models.CharField(max_length=64)),
                ('payment_request_id', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('longurl', models.URLField()),
                ('shorturl', models.URLField()),
                ('status', models.CharField(max_length=16)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=512)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('AP', 'ANDHRA PRADESH'), ('AR', 'ARUNACHAL PRADESH'), ('AS', 'ASSAM'), ('BR', 'BIHAR'), ('CG', 'CHATTISGARH'), ('DL', 'DELHI'), ('GA', 'GOA'), ('GJ', 'GUJARAT'), ('HR', 'HARYANA'), ('HP', 'HIMACHAL PRADESH'), ('JK', 'JAMMU & KASHMIR'), ('JS', 'JHARKHAND'), ('KA', 'KARNATAKA'), ('MP', 'MADHYA PRADESH'), ('MH', 'MAHARASHTRA'), ('MN', 'MANIPUR'), ('ML', 'MEGHALAYA'), ('MZ', 'MIZORAM'), ('NL', 'NAGALAND'), ('OR', 'ORISSA'), ('PB', 'PUNJAB'), ('RJ', 'RAJASTHAN'), ('SK', 'SIKKIM'), ('TN', 'TAMIL NADU'), ('TR', 'TRIPURA'), ('UK', 'UTTARAKHAND'), ('UP', 'UTTAR PRADESH'), ('WB', 'WEST BENGAL'), ('AN', 'ANDAMAN & NICOBAR'), ('CH', 'CHANDIGARH'), ('DN', 'DADAR & NAGAR HAVELI'), ('DD', 'DAMAN & DIU'), ('LD', 'LAKSHADWEEP'), ('PY', 'PONDICHERRY')], max_length=2)),
                ('postal_code', models.CharField(max_length=8)),
                ('phone_mobile', models.CharField(max_length=13)),
                ('phone_landline', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
